language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
    - jdk: openjdk11
  allow_failures:
    - jdk: openjdk11

before_install:
  - unset _JAVA_OPTIONS
cache:
  directories:
  - $HOME/.m2
